# Generated by Django 5.0.6 on 2024-06-03 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_cart_product_remove_cart_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='created_at',
        ),
    ]
