# Generated by Django 5.0.6 on 2024-06-17 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_notification'),
    ]

    operations = [
    ]
